version: '3.7'
services: 
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    volumes:
      - postgres_data:/postgresql

volumes:
  postgres_data:
  
    